#--------------------------------------------------------------------------------------------------------------#
                                   #Keystore Configurations#
#--------------------------------------------------------------------------------------------------------------#
keyStorePath: "keystore-cloudhub.jks"
alias: "cloudhub"


#O------------------------------------------------------------------------------------------------------------O#
                                    # Mule Service Endpoint
#O-------------------------------------------------------------------------------------------------------------O#
api:
  name: "SeviceNow API"
  version: "1.0"
autoDiscoverApiId: "15856011"
#---------------------------------------------------------------------------------------------------------------#
                                    #ESB-api HTTP config#
#O--------------------------------------------------------------------------------------------------------------O#
https:
  host: "0.0.0.0"
  path: "/api"

#O---------------------------------------------------------------------------------------------------------------O#
                                      #SFTP Configurations
#O---------------------------------------------------------------------------------------------------------------O#

sftp:
  host: "tc3vmdevfp1.tccrocks.com"
  port: "22"
  username: "![n0PlZRF5AlDRxhRxSFCYIw==]"
  password: "![eamcbPlEuBg8N3EtqPRkMg==]"
  
#O---------------------------------------------------------------------------------------------------------------O#
                                      #ServiceNow  Configurations
#O---------------------------------------------------------------------------------------------------------------O#

sn:
  protocol: "HTTPS"
  host: "tccincdev.service-now.com"
  path: "/api/now/v1/table/incident"
  attachment: "/api/now/attachment/file"
  user: "![zV1dgUEf9Roh3k7Dl9zD+E5tPq6ijUc+p40FBxmP/QE=]"
  pwd: "![AUfqPb2PJSntPGKfSlwhsw==]"