#--------------------------------------------------------------------------------------------------------------#
                                   #Keystore Configurations#
#--------------------------------------------------------------------------------------------------------------#
keyStorePath: "keystore-cloudhub.jks"
alias: "cloudhub"

#O------------------------------------------------------------------------------------------------------------O#
                                    # Mule Service Endpoint
#O-------------------------------------------------------------------------------------------------------------O#
api:
  name: "SeviceNow API"
  version: "1.0"
autoDiscoverApiId: "15856026"
#---------------------------------------------------------------------------------------------------------------#
                                    #ESB-api HTTP config#
#O--------------------------------------------------------------------------------------------------------------O#
https:
  host: "0.0.0.0"
  path: "/api"

#O---------------------------------------------------------------------------------------------------------------O#
                                      #SFTP Configurations
#O---------------------------------------------------------------------------------------------------------------O#

sftp:
  host: "tc3vmprdfp1.tccrocks.com"
  port: "22"
  username: "![cT4w/0QzMwlRWWGVcNETLw==]"
  password: "![eTOMTLS9bpCI1fTJXKk5wg==]"
  
#O---------------------------------------------------------------------------------------------------------------O#
                                      #ServiceNow  Configurations
#O---------------------------------------------------------------------------------------------------------------O#

sn:
  protocol: "HTTPS"
  host: "tccinc.service-now.com"
  path: "/api/now/v1/table/incident"
  attachment: "/api/now/attachment/file"
  user: "![mLxdlromYmZjfXTMGEc0rBCUfxbd5RVV8eCzuTJHmyM=]"
  pwd: "![lDgJFDugEYAey4JJSfh6DQ==]"
