#%RAML 0.8
title: Jde Service
version: v1.0
baseUri: http://10.206.14.6:8081/api/v1.0/jde-esb-service
protocols: [HTTP, HTTPS]
mediaType: application/json         
/creditCheckARAccountBalance:
  displayName: Credit Check Account Balance 
  post:  
    body: 
      application/json: 
       example: !include requestCreditCheck.json
       schema: !include requestCreditCheckSchema.json
    
    responses: 
      200: 
        body: 
          application/json: 
            example: !include responseCreditCheck.json
            schema: !include responseCreditCheckSchema.json
          
      400: 
        body: 
          application/json: 
           example : |
              {
                      "errorResponse": {
                      "description": "Resource URL Error" ,
                      "status": 400              
                     }
                 }
      
      500: 
        body: 
          application/json:
             example : |
              {
                      "errorResponse": {
                      "description": "Server Error" ,
                      "status": 500              
                     }
                } 
/create-update-customer:
   displayName: Create / Update Customer to JDE
   description: |
    Create/Update Customer Information to JDE
   post: 
    body: 
      application/json: 
        example: !include CreateOrUpdateCustomer.json
        schema: !include CreateOrUpdateCustomer-Schema.json
        
    responses: 
      200: 
        body:  
          application/json: 
            
      500: 
        body:  
          application/json:
            example: |
             {
              "errorMessage": {
              "description": "Server Error",             
               "status": 500
               }
             }
      400: 
        body: 
          application/json: 
            example: |
             {
        
              "errorMessage": {
              "description": "Resource URL Error", 
              "status": 400
                      }
             }
      404: 
        body: 
          application/json: 
            example: |
             {
              "errorMessage": {
              "description": "Incorrect URL",                    
              "status": 404
                      } 
             } 
             
/create-update-salesorder:
   displayName: Create / Update Salesorder to JDE
   description: |
    Create/Update Customer Salesorder to JDE
   post: 
    body: 
      application/json: 
        example: !include salesorder-jde.json
        schema: !include salesorder-jde-schema.json
        
    responses: 
      200: 
        body:  
          application/json: 
            
      500: 
        body:  
          application/json:
            example: |
             {
              "errorMessage": {
              "description": "Server Error",             
               "status": 500
               }
             }
      400: 
        body: 
          application/json: 
            example: |
             {
        
              "errorMessage": {
              "description": "Resource URL Error", 
              "status": 400
                      }
             }
      404: 
        body: 
          application/json: 
            example: |
             {
              "errorMessage": {
              "description": "Incorrect URL",                    
              "status": 404
                      } 
             }