#%RAML 0.8
---
title: system-rebiz
version: v1.0
baseUri: http://10.206.14.6:8081/
protocols: [HTTP, HTTPS]
mediaType: application/json

/db/rebiz:
  post:
    description: Store rebiz to DB
    body:
      application/json:
        example: !include req.json
        schema: !include req-schema.json
    responses: 
      200: 
        body: 
          application/json: 
            example: |
              {
                "success": {
                  "code": "200",
                  "message": "Rebiz- pushed to DB Successfully"
                 }
              }
      500: 
       body: 
        application/json: 
          example: |
            {
              "error":{
                "errorCode":"500",
                "errorMessage":"Rebiz- Failed to push into DB"
              }
            }  
                            
/db/rebiz_insertion:
  post:
    description: Store rebiz to DB- Only Insertion
    body:
      application/json:
        example: !include req.json
        schema: !include req-schema.json
    responses: 
      200: 
        body: 
          application/json: 
            example: |
              {
                "success": {
                  "code": "200",
                  "message": "Rebiz- pushed to DB Successfully"
                 }
              }
      500: 
       body: 
        application/json: 
          example: |
            {
              "error":{
                "errorCode":"500",
                "errorMessage":"Rebiz- Failed to push into DB"
              }
            }              