INSERT INTO CONTACTS(CONTACT_ID,CONTACT_NAME,CONTACT_TYPE,PHONE,EMAIL,PREFERED_MODE) VALUES (1,'ESB_SUPPORT','EMAIL',NULL,'stonne@tccrocks.com','EMAIL');
INSERT INTO CONTACTS(CONTACT_ID,CONTACT_NAME,CONTACT_TYPE,PHONE,EMAIL,PREFERED_MODE) VALUES (2,'ATG_SUPPORT','EMAIL',NULL,'rvenugopal@tccrocks.com,','EMAIL');
INSERT INTO CONTACTS(CONTACT_ID,CONTACT_NAME,CONTACT_TYPE,PHONE,EMAIL,PREFERED_MODE) VALUES (3,'ATG_SUPPORT','EMAIL',NULL,'ppawar@tccrocks.com','EMAIL');
INSERT INTO CONTACTS(CONTACT_ID,CONTACT_NAME,CONTACT_TYPE,PHONE,EMAIL,PREFERED_MODE) VALUES (4,'ESB_SUPPORT','EMAIL',NULL,'rvalsarajan@tccrocks.com','EMAIL');
INSERT INTO CONTACTS(CONTACT_ID,CONTACT_NAME,CONTACT_TYPE,PHONE,EMAIL,PREFERED_MODE) VALUES (5,'ESB_SUPPORT','EMAIL',NULL,'auppin@tccrocks.com','EMAIL');
INSERT INTO CONTACTS(CONTACT_ID,CONTACT_NAME,CONTACT_TYPE,PHONE,EMAIL,PREFERED_MODE) VALUES (6,'ESB_SUPPORT','EMAIL',NULL,'sbasha@tccrocks.com','EMAIL');
INSERT INTO CONTACTS(CONTACT_ID,CONTACT_NAME,CONTACT_TYPE,PHONE,EMAIL,PREFERED_MODE) VALUES (7,'ESB_SUPPORT','EMAIL',NULL,'avenkatesh@tccrocks.com','EMAIL');
commit;