#%RAML 1.0
---
title: ServiceNow API
baseUri: http://localhost:8082/servicenowincident

/createIncident:
  displayName: create incident in serviceNow
  description: |
    This operation is used to create incident in serviceNow
  post: 
    body:
    
    responses:
      201:
        body:
          application/json: 
            example: |
              {
                "successMessage": {
                    "description": "Created Incident Successfully",
                    "status": 201
                    }
                  }  
    
      
/getIncident:
  displayName: retrieve's incident details from serviceNow
  description: |
    This operation is used to retrieve incident details from serviceNow
  get: 
    body: 
    
    responses:
      200:
        body:
          application/json: 
             example: |
              {
                "successMessage": {
                  "descrption": "incident details retrieved successfully"
                  
            
        
   

/updateIncident:
  displayName: updates existing incident in serviceNow
  description: |
    This operation checks from the incident if present, update the existing incident in serviceNow
  put: 
    body:
    
    responses:
      200: 
        body:
          application/json:
            example: |  
              {
              "successMessage": {
                 "description": "Modified Incident Successfully",
                 "status": 200
                 }
               }

/upsertIncident:
  displayName: Upsert incident
  description: |
     This operation is used to update the existing incident if found and if not, create a new incident in serviceNow  
  put: 
    body:
    
    responses: 
      200:
        body:
          application/json: 
            example: |
              {
                "successMessage": {
                  "description": "Modified incident Successfully",
                   "status": 200
                   }
                }
                   
           
   

     